server:
  port: 8888
  servlet:
    context-path: /build
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mes?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
logging:
  file:
    name: build.log
    path: logs/
mybatis-plus:
  global-config:
    banner: off
